name: build-windows-wheel

on: [push, workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheel on windows-latest
    runs-on: windows-latest
    # This keeps it from running on every single branch if you only want master/tags
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          # Targets only CPython 3.12 for Windows 64-bit
          CIBW_BUILD: "cp312-win_amd64"
          CIBW_TEST_REQUIRES: "pytest scikit-learn"
          CIBW_BEFORE_BUILD: "pip install numpy>=2.0.0"
          CIBW_BEFORE_BUILD_WINDOWS: "pip install numpy>=2.0.0 delvewheel"
          # delvewheel is important for Windows to bundle necessary DLLs
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel show {wheel} && delvewheel repair -w {dest_dir} {wheel}"
          CIBW_TEST_COMMAND: "pytest {package}/test"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-python-312-wheel
          path: ./wheelhouse/*.whl
